### PR TITLE
Fixing yield in iter module

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
It keep printing date in console for ever.
For ex:
2017-12-12T13:39:00.340Z
2017-12-12T13:39:00.340Z
2017-12-12T13:39:00.340Z
....
And there will be no way to stop the iterations.

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
Test script:

```
import haloscans

key='<key>'
secret='<secret>'
target_date='<scan_date>' # For ex: '2017-12-11'
api_host='api.cloudpassage.com'
search_params = {"since": target_date, "sort_by": "created_at.asc"}
scans = haloscans.HaloScans(key, secret, api_host=api_host, search_params=search_params)
for scan in scans:
            if not scan["created_at"].startswith(target_date):
                print("No more scans for target day!")
                raise StopIteration
            else:
                print 'ScanID: ' + scan["id"]
```

**Comment by ashmastaflash** [comment]
Hi @anuragpaliwal80, thanks for the PR!

This library was written to be used inside a long-running collector, similar to the way the event connector (https://github.com/cloudpassage/connector) works, but for scans.

For collecting a single day's scans (and optionally shipping them to S3), I made the `halo-scans-archiver` tool, which breaks when the date no longer matches the target date.  If you use the `halo-scans-archiver` tool to query for the current date, it should continue until the first of the next day's scans gets published via the api, at which point the tool should exit (see https://github.com/cloudpassage/halo-scans-archiver/blob/master/tool/scanslib/get_scans.py#L16)

In the first example below, your example script throws a `StopIteration` when the first of the scans from `2017-12-12` comes from the API, because the target date is `2017-12-11`.

In the second example below, I had to use ctrl-c because scans from `2017-12-13` haven't come from the api; I would have to wait until tomorrow for the `StopIteration` to be raised.

```
>>> import os
>>> key = os.getenv("HALO_API_KEY")
>>> secret = os.getenv("HALO_API_SECRET_KEY")
>>> import haloscans
>>> 
>>> target_date='2017-12-11'
>>> api_host='api.cloudpassage.com'
>>> search_params = {"since": target_date, "sort_by": "created_at.asc"}
>>> scans = haloscans.HaloScans(key, secret, api_host=api_host, search_params=search_params)
>>> for scan in scans:
...     if not scan["created_at"].startswith(target_date):
...         print("No more scans for target day!")
...         raise StopIteration
...     else:
...         print 'ScanID: ' + scan["id"]
... 
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
No more scans for target day!
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
StopIteration
```

```
>>> target_date='2017-12-12'
>>> search_params = {"since": target_date, "sort_by": "created_at.asc"}
>>> scans = haloscans.HaloScans(key, secret, api_host=api_host, search_params=search_params)
>>> for scan in scans:
...     if not scan["created_at"].startswith(target_date):
...         print("No more scans for target day!")
...         raise StopIteration
...     else:
...         print 'ScanID: ' + scan["id"]
... 
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
ScanID: some_scan_id
2017-12-12T12:59:27.729Z
2017-12-12T12:59:27.729Z
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "haloscans/haloscans.py", line 43, in __iter__
    for scan in self.get_next_batch():
  File "haloscans/haloscans.py", line 76, in get_next_batch
    time.sleep(30)
KeyboardInterrupt
```


Thanks again for the PR, and for using the library.  Let me know if I'm missing some context for your request, or if I'm misunderstanding the nature of your submission.

**Comment by anuragpaliwal80** [comment]
Thanks for explaining in detail and for your prompt reply.
I was executing the my above query for the date which have some scans results. After showing the scans id, it started showing  `2017-12-12T13:39:00.340Z` forever as code never comes back to `for scan in scans:` block and hence was not able to `raise StopIteration`.

But after my changes it comes back to `for scan in scans:` block and hence was able to `raise StopIteration`.

**Comment by ashmastaflash** [comment]
I want to get a better understanding of your use case so that I can accommodate it, hopefully without losing specific functionality I wrote into the library.

The original use case this was written for was a scan consumer that runs forever, writing scan json documents to disk as they are published in the API.  Blocking in the event there are no more scans is the desired behavior in this case.

The daily scan shipper that uses this library raises a StopIteration when this library's iterator returns a scan with a date that doesn't match the desired date.  If the tool is run for the current day, it will continue to run until all the day's scans are consumed, and the first of the next day's scans will cause the tool to exit cleanly.

If this library raises a StopIteration when there are no more scans available, the perpetual scan consumer won't work, or will require a substantial refactoring.

I would love to hear more about your specific use case.  I may even have some code in a non-public repo that does exactly what you want.

I think I have your email address.  I'll reach out to you directly to get the details for your use case.

**Pull request closed without merging**
